# Generated by Django 4.0.3 on 2022-04-09 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_losses_alter_user_pushes_alter_user_wins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='return_31',
        ),
    ]
