# Generated by Django 4.0.3 on 2022-04-10 03:41
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecapr', '0002_bet_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet',
            name='bet_market',
        ),
        migrations.AddField(
            model_name='bet',
            name='event_date',
            field=models.DateField(default=datetime.date(2022, 4, 10)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bet',
            name='bet_type',
            field=models.CharField(max_length=75),
        ),
    ]
