# Generated by Django 4.0.3 on 2022-04-10 03:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecapr', '0003_remove_bet_bet_market_bet_event_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='event_date',
            field=models.DateField(default=datetime.date(2022, 4, 10)),
        ),
    ]
