# Generated by Django 4.0.3 on 2022-04-10 03:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecapr', '0004_alter_bet_event_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet',
            name='event_date',
        ),
        migrations.AddField(
            model_name='bet',
            name='event_finish',
            field=models.DateField(default=datetime.date(2022, 4, 10)),
        ),
    ]
