# Generated by Django 4.0.3 on 2022-04-11 22:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecapr', '0005_remove_bet_event_date_bet_event_finish'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='pot_win',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bet',
            name='event_finish',
            field=models.DateField(default=datetime.date(2022, 4, 11)),
        ),
    ]
