# Generated by Django 4.0.3 on 2022-04-17 07:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecapr', '0008_bet_profit_alter_bet_event_finish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='event_finish',
            field=models.DateField(default=datetime.date(2022, 4, 17)),
        ),
    ]
